services:
  app:
    image: evgeniygorban/resume:MyResume
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume_app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - NODE_ENV=production
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_name=${DB_name}
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: